export const Team = [
  {
    firstName: 'Ace',
    lastName: 'Baugh',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Annie',
    lastName: 'Andrejek',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Anton',
    lastName: 'Ortiz Campos',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Aviv',
    lastName: 'Shazar',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Casey',
    lastName: "O'Donahoe",
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Charlene',
    lastName: 'Creighton',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Corey',
    lastName: 'Cobus',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Darren',
    lastName: 'Rauer',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Geoff',
    lastName: 'Biby',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Greg',
    lastName: 'Rau',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Heather',
    lastName: 'Dangren',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Matt',
    lastName: 'Oberlin',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Paul',
    lastName: 'Hinz',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Remon',
    lastName: 'Ghatas',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Royal',
    lastName: 'Hawkins',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Shawn',
    lastName: 'Safdar',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Simon',
    lastName: 'Yu',
    hasGone: false,
    showPhoto: true,
  },
];
