export const Team = [
  {
    firstName: 'Remon',
    lastName: 'Ghatas',
    photo: 'remon.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Annie',
    lastName: 'Andrejek',
    photo: 'annie.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Ace',
    lastName: 'Baugh',
    photo: 'ace.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Geoff',
    lastName: 'Biby',
    photo: 'geoff.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Corey',
    lastName: 'Cobus',
    photo: 'corey.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Cody',
    lastName: 'Crampton',
    photo: 'cody.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Charlene',
    lastName: 'Creighton',
    photo: 'charlene.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Heather',
    lastName: 'Dangren',
    photo: 'heather.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Paul',
    lastName: 'Hinz',
    photo: 'paul.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Casey',
    lastName: "O'Donahoe",
    photo: 'casey.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Anton',
    lastName: 'Ortiz Campos',
    photo: 'anton.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Greg',
    lastName: 'Rau',
    photo: 'greg.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Darren',
    lastName: 'Rauer',
    photo: 'darren.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Shawn',
    lastName: 'Safdar',
    photo: 'shawn.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Aviv',
    lastName: 'Shazar',
    photo: 'aviv.jpg',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Simon',
    lastName: 'Yu',
    photo: 'simon.jpg',
    hasGone: false,
    showPhoto: true,
  },
];
