export const Team = [
  {
    firstName: 'Jenson',
    lastName: 'Wells',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Paisley',
    lastName: 'Manning',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Kaius',
    lastName: 'Rocha',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Sage',
    lastName: 'Fisher',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Rowan',
    lastName: 'Olsen',
    hasGone: false,
    showPhoto: false,
  },
  {
    firstName: 'Willow',
    lastName: 'Pierce',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Beckett',
    lastName: 'Crawford',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Caspian',
    lastName: 'Reed',
    hasGone: false,
    showPhoto: false,
  },
  {
    firstName: 'Orion',
    lastName: 'Patel',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Caelum',
    lastName: 'Hall',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Lylah',
    lastName: 'Davenport',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Gideon',
    lastName: 'Barnes',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Magnus',
    lastName: 'Harrison',
    hasGone: false,
    showPhoto: false,
  },
  {
    firstName: 'Zayden',
    lastName: 'Gomez',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Thane',
    lastName: 'Singh',
    hasGone: false,
    showPhoto: true,
  },
  {
    firstName: 'Kieran',
    lastName: 'Wallace',
    hasGone: false,
    showPhoto: true,
  },
];
